name: gitleaks
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }  # necesario para escaneo de historia
      - name: Run gitleaks
        uses: gitleaks/gitleaks-action@v2
        with:
          args: "detect --config ci/gitleaks-allowlist.toml --source . --no-git -v"
      # Si prefieres fallar el build ante hallazgos, añade: --exit-code 1
